name: unit_testing

on:
  pull_request:
    branches: [ "main" ]

jobs:
  unit-testing:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with: {java-version: 1.8}
      - name: Change access
        run: chmod 777 ./gradlew
      - name: Run unit tests
        run: ./gradlew test
