name: unit_testing

on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "development" ]

jobs:
  unit-testing:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with: {java-version: 1.8}
      - name: Change access
        run: cd quizz_app && chmod 777 gradlew
      - name: Run unit tests
        run: quizz_app/gradlew test
      - name: Test Reporter
        uses: dorny/test-reporter@v1.6.0
      - uses: actions/upload-artifact@v2  # upload test results
        if: success() || failure()        # run this step even if previous step failed
        with:
          name: test-results
          path: jest-junit.xml
