name: unit_testing

on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "development" ]

jobs:
  unit-testing-and-assembling:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with: {java-version: 11}
      - name: Change access
        run: cd quizz_app && chmod 777 gradlew
      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle
      - name: Run unit tests
        run: cd quizz_app && ./gradlew clean && ./gradlew test && ./gradlew assembleRelease && ./gradlew bundleRelease
      - name: Upload .apk
        uses: actions/upload-artifact@v3
        with:
          name: QuizzAPK
          path: quizz_app/app/build/outputs/apk/release/app-release-unsigned.apk
      - name: Upload AAB Bundle
        uses: actions/upload-artifact@v3
        with:
          name: QizzAAB
          path: quizz_app/app/build/outputs/bundle/release/app-release.aab
 
  run_ui_tests_on_firebase:
    runs-on: ubuntu-20.04
    needs: unit-testing-and-assembling
    steps:
      - uses: actions/checkout@v3
      - name: Download EasyQuizz APK
        uses: actions/download-artifact@v3
        with:
          name: QuizzAPK
 
      - name: Firebase auth
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.FIREBASE_KEY }}
          project_id: ${{ secrets.FIREBASE_PROJECT_ID }}
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.FIREBASE_PROJECT_ID }}
 
      - name: Run UI tests in cloud
        run: |
          chmod +wx quizz_app
          gcloud firebase test android models list
          gcloud firebase test android run --app app-release-unsigned.apk --robo-script quizz_app/app/src/ui_test/MainActivity_robo_script.json --device model=Pixel2,version=28,locale=en,orientation=portrait
