name: unit_testing

on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "development" ]

jobs:
  unit-testing:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with: {java-version: 11}
      - name: Change access
        run: cd quizz_app && chmod 777 gradlew
      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle
      - name: Run unit tests
        run: cd quizz_app && ./gradlew clean && ./gradlew test --stacktrace
      - name: Report
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: Unit Tests
          path: reports/jest-junit.xml
          reporter: java-junit
          fail-on-error: true
