name: unit_testing

on:
  pull_request:
    branches: [ "main" ]

jobs:
  unit-testing:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with: {java-version: 1.8}
      - name: Cd to project
        run: cd ./quizz_app
      - name: Change access
        run: chmod 777 ./gradlew
      - name: Run unit tests
        run: ./gradlew test
      - uses: actions/upload-artifact@v2  # upload test results
        if: success() || failure()        # run this step even if previous step failed
        with:
          name: test-results
          path: jest-junit.xml
